# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  vim
)

source $ZSH/oh-my-zsh.sh

# Set vi keybindings (remove emacs mode and duplicates below)
bindkey -v
export KEYTIMEOUT=1

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
# Add important directories to PATH, preserving existing PATH
export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:$HOME/anaconda3/bin"

export JAVA_HOME=/usr/lib/jvm/java-8-oracle
export PYSPARK_PYTHON="$HOME/anaconda3/envs/sigil36/bin/python"
export SPARK_LOCAL_IP=127.0.0.1

export SPARK_HOME=/usr/local/spark
export HADOOP_HOME=/usr/local/hadoop
export AMBARI_CONF_DIR=/usr/local/hadoop/etc/docker_ambari_cluster_conf
export HADOOP_CONF_DIR=$AMBARI_CONF_DIR/full_client_conf

export PATH="$PATH:$SPARK_HOME/bin:$HADOOP_HOME/bin"

# Custom functions
tsv2nl() {
    sed 's/\t/\n/g' "$1" | awk ' BEGIN { cc = 0 } { cc += 1; printf("%2d: %s\n", cc, $0) } '
}

csv2nl() {
    sed 's/,/\n/g' "$1" | awk ' BEGIN { cc = 0 } { cc += 1; printf("%2d: %s\n", cc, $0) } '
}

# Aliases
alias t=todo.sh
alias gre='grep -En'
alias antlr4='java -Xmx500M -cp /usr/local/lib/antlr-4.7.1-complete.jar: org.antlr.v4.Tool'
alias grun='java org.antlr.v4.gui.TestRig'

# Notes and tools
export NOTES_DIR="$HOME/Desktop/notes"
export IMPALA_HOME="$HOME/apache-impala-3.0.1"

# CLASSPATH
export CLASSPATH="/usr/local/lib/antlr-4.7.1-complete.jar${CLASSPATH:+:$CLASSPATH}"

# Keybindings
bindkey '^R' history-incremental-search-backward

# Fallback system-agnostic prompt if theme is not set
if [[ -z "$ZSH_THEME" || "$ZSH_THEME" == "none" ]]; then
  PS1="%n@%m %1~ %# "
fi
